import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:sizer/sizer.dart';
import 'package:share_plus/share_plus.dart';
import 'package:intl/intl.dart';


/// Privacy Policy Generator - Creates comprehensive privacy documentation
class PrivacyPolicyGeneratorScreen extends StatefulWidget {
  const PrivacyPolicyGeneratorScreen({super.key});

  @override
  State<PrivacyPolicyGeneratorScreen> createState() =>
      _PrivacyPolicyGeneratorScreenState();
}

class _PrivacyPolicyGeneratorScreenState
    extends State<PrivacyPolicyGeneratorScreen> {
  String _selectedJurisdiction = 'GDPR';
  String _generatedPolicy = '';
  bool _isGenerating = false;

  final List<String> _jurisdictions = ['GDPR', 'CCPA', 'PIPEDA', 'Generic'];

  @override
  void initState() {
    super.initState();
    _generatePolicy();
  }

  void _generatePolicy() {
    setState(() {
      _isGenerating = true;
    });

    Future.delayed(const Duration(milliseconds: 500), () {
      setState(() {
        _generatedPolicy = _buildPolicyText();
        _isGenerating = false;
      });
    });
  }

  String _buildPolicyText() {
    final lastUpdated = DateFormat('MMMM dd, yyyy').format(DateTime.now());

    return '''
QUIETCHECK PRIVACY POLICY
Last Updated: $lastUpdated
Jurisdiction: $_selectedJurisdiction

1. INTRODUCTION

QuietCheck ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, and safeguard your personal information when you use our mobile application.

2. DATA COLLECTION

We collect the following types of data:

a) Device Usage Patterns:
   - Screen unlock frequency
   - App switching velocity
   - Session duration
   - Device interaction intensity

b) Health & Wellness Data (Optional, User-Consented):
   - Heart rate and heart rate variability
   - Sleep duration and quality
   - Physical activity and step count
   - Movement patterns

c) Technical Data:
   - Device type and operating system
   - App version and build information
   - Crash reports and error logs (debug builds only)

3. DATA PROCESSING

ALL DATA IS PROCESSED LOCALLY ON YOUR DEVICE. We do not:
- Transmit data to external servers
- Share data with third parties
- Use cloud storage for personal data
- Implement tracking or analytics SDKs
- Display advertisements

4. DATA STORAGE

All data is:
- Encrypted at rest using AES-256 encryption
- Stored locally on your device only
- Protected by platform-specific secure storage (Android Keystore / iOS Keychain)
- Never synchronized to cloud services

5. DATA RETENTION

You control your data:
- Historical data is kept for up to 90 days for trend analysis
- You can delete all data at any time through Settings
- Uninstalling the app permanently removes all data

6. USER RIGHTS

You have the right to:
- Access your data through the app's export feature
- Delete your data at any time
- Control which data types are collected
- Revoke permissions at any time

${_getJurisdictionSpecificText()}

7. PERMISSIONS EXPLAINED

a) Usage Access (Android) / Screen Time (iOS):
   Purpose: Monitor device interaction patterns to detect behavioral changes
   Data: Aggregate usage statistics only, no app content

b) Health Data (Optional):
   Purpose: Detect physiological stress indicators
   Data: Heart rate, HRV, sleep, steps (user must explicitly grant access)

c) Motion & Activity:
   Purpose: Detect sedentary periods and movement patterns
   Data: Activity type (walking, stationary, etc.)

d) Notifications:
   Purpose: Deliver mental load alerts and recovery reminders
   Data: None collected, only used for delivery

8. SUBSCRIPTION DATA

Subscription management is handled by:
- Google Play Billing (Android)
- Apple App Store (iOS)

We do not store payment information. Subscription status is stored locally and encrypted.

9. SECURITY MEASURES

- AES-256-CBC encryption for all stored data
- Secure key storage using platform keystores
- No network transmission of personal data
- Regular security audits
- Minimal data collection principle

10. CHILDREN'S PRIVACY

QuietCheck is not intended for users under 13 years of age. We do not knowingly collect data from children.

11. CHANGES TO THIS POLICY

We may update this policy to reflect changes in our practices or legal requirements. Updates will be posted in-app with the revision date.

12. CONTACT INFORMATION

For privacy-related questions:
Email: privacy@quietcheck.app
Website: https://quietcheck.app/privacy

13. LEGAL DISCLAIMER

This privacy policy is provided for informational purposes. For legal compliance in your jurisdiction, please consult with a qualified attorney.

---

GENERATED BY: QuietCheck Privacy Policy Generator
VERSION: 1.0
DATE: $lastUpdated
''';
  }

  String _getJurisdictionSpecificText() {
    switch (_selectedJurisdiction) {
      case 'GDPR':
        return '''
6.1 GDPR-SPECIFIC RIGHTS (European Union)

Under GDPR, you have additional rights:
- Right to data portability (export your data)
- Right to be forgotten (delete all data)
- Right to restrict processing
- Right to object to processing
- Right to lodge a complaint with supervisory authority

Legal Basis for Processing:
- Consent (for health data collection)
- Legitimate interest (for app functionality)
''';
      case 'CCPA':
        return '''
6.1 CCPA-SPECIFIC RIGHTS (California)

Under CCPA, you have the right to:
- Know what personal information is collected
- Know whether personal information is sold or disclosed
- Say no to the sale of personal information (we do not sell data)
- Access your personal information
- Request deletion of personal information
- Not be discriminated against for exercising your rights
''';
      case 'PIPEDA':
        return '''
6.1 PIPEDA-SPECIFIC RIGHTS (Canada)

Under PIPEDA, we adhere to:
- Accountability for data protection
- Identifying purposes for data collection
- Obtaining consent for collection, use, or disclosure
- Limiting collection to necessary data
- Limiting use, disclosure, and retention
- Ensuring accuracy of personal information
- Safeguarding personal information
- Openness about data management policies
- Individual access to personal information
- Challenging compliance
''';
      default:
        return '';
    }
  }

  Future<void> _copyToClipboard() async {
    await Clipboard.setData(ClipboardData(text: _generatedPolicy));
    if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Privacy policy copied to clipboard')),
      );
    }
  }

  Future<void> _sharePolicy() async {
    await Share.share(_generatedPolicy, subject: 'QuietCheck Privacy Policy');
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Privacy Policy Generator'),
        actions: [
          IconButton(
            icon: const Icon(Icons.copy),
            onPressed: _copyToClipboard,
            tooltip: 'Copy to clipboard',
          ),
          IconButton(
            icon: const Icon(Icons.share),
            onPressed: _sharePolicy,
            tooltip: 'Share',
          ),
        ],
      ),
      body: Column(
        children: [
          // Jurisdiction selector
          Container(
            padding: EdgeInsets.all(4.w),
            color: theme.colorScheme.surfaceContainerHighest,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text('Select Jurisdiction', style: theme.textTheme.titleMedium),
                SizedBox(height: 1.h),
                DropdownButtonFormField<String>(
                  initialValue: _selectedJurisdiction,
                  decoration: const InputDecoration(
                    border: OutlineInputBorder(),
                    contentPadding: EdgeInsets.symmetric(
                      horizontal: 12,
                      vertical: 8,
                    ),
                  ),
                  items: _jurisdictions.map((jurisdiction) {
                    return DropdownMenuItem(
                      value: jurisdiction,
                      child: Text(jurisdiction),
                    );
                  }).toList(),
                  onChanged: (value) {
                    if (value != null) {
                      setState(() {
                        _selectedJurisdiction = value;
                      });
                      _generatePolicy();
                    }
                  },
                ),
                SizedBox(height: 1.h),
                Text(
                  'Last updated: ${DateFormat('MMM dd, yyyy').format(DateTime.now())}',
                  style: theme.textTheme.bodySmall,
                ),
              ],
            ),
          ),

          // Policy preview
          Expanded(
            child: _isGenerating
                ? const Center(child: CircularProgressIndicator())
                : SingleChildScrollView(
                    padding: EdgeInsets.all(4.w),
                    child: SelectableText(
                      _generatedPolicy,
                      style: TextStyle(fontSize: 13.sp, height: 1.5),
                    ),
                  ),
          ),

          // Legal disclaimer
          Container(
            padding: EdgeInsets.all(4.w),
            color: Colors.amber.shade100,
            child: Row(
              children: [
                Icon(Icons.warning, color: Colors.amber.shade900),
                SizedBox(width: 2.w),
                Expanded(
                  child: Text(
                    'Legal Disclaimer: This generated policy is a template. Consult with a qualified attorney for legal compliance.',
                    style: TextStyle(
                      fontSize: 12.sp,
                      color: Colors.amber.shade900,
                    ),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
